/**
 * Author:  Cristobal Barrios
 * Created: 4 de out. de 2024
 */

-- CREAR TABLA DE USUARIOS
CREATE TABLE PROYECTO.TBLUSUARIOS 
(
  IDUSUARIO NUMBER GENERATED ALWAYS AS IDENTITY	
, USUARIO VARCHAR2(50) NOT NULL 
, PASSWORD VARCHAR2(100) NOT NULL 
, CONSTRAINT TBLUSUARIOS_PK PRIMARY KEY 
  (
    IDUSUARIO 
  )
  ENABLE 
);

-- INSERTAR USUARIO INICIAL
INSERT INTO "PROYECTO"."TBLUSUARIOS" (USUARIO, PASSWORD) VALUES ('admin', 'admin');
COMMIT;